--County(County ID, Name)
INSERT INTO County Values(1, 'Wicklow')
INSERT INTO County Values(2, 'Dublin')
INSERT INTO County Values(3, 'Kildare')
INSERT INTO County Values(4, 'Carlow')
INSERT INTO County Values(5, 'Cork')
INSERT INTO County Values(6, 'Meath')
INSERT INTO County Values(7, 'Mayo')

--Board_Member(PPS Number, County ID, Name, Phone Number, Address)
INSERT INTO Board_Member Values(100000000, 1, 'John Smith', 0871234567, '1 main road, Kilmac, Wicklow')
INSERT INTO Board_Member Values(100000001, 2, 'April Long', 0871234267, '10 left road, Dalkey, Dublin')
INSERT INTO Board_Member Values(100000002, 3, 'Dan Tilley', 0871524567, '63 Dark lane, Leixslip, Kildare')
INSERT INTO Board_Member Values(100000003, 4, 'Paul Freehy', 0871238267, 'Number 6, Borris, Carlow')
INSERT INTO Board_Member Values(100000004, 5, 'Andrew Byrne', 0861234567, 'Howardshore, Ballyhea, Cork')
INSERT INTO Board_Member Values(100000005, 6, 'Damien Rice', 0871234907, 'Damiens Castle, Trim, Meath')
INSERT INTO Board_Member Values(100000006, 7, 'Dermot Kennedy', 0871239007, 'Eoins Den, Westport, Mayo')

--Division(ID, Name, County ID)
INSERT INTO Division Values(1, 'Senior', 1)
INSERT INTO Division Values(2, 'Intermediate', 1)
INSERT INTO Division Values(3, 'Junior', 1)
INSERT INTO Division Values(4, 'Senior', 2)
INSERT INTO Division Values(5, 'Senior', 3)
INSERT INTO Division Values(6, 'Intermediate', 3)

--Team(ID, Division ID, Team Name, Town Name)
INSERT INTO Team Values(1, 1, 'Rathnew GAA', 'Rathnew')
INSERT INTO Team Values(2, 1, 'St. Patricks GAA', 'Wicklow Town')
INSERT INTO Team Values(3, 2, 'Kilmacanogue GAA', 'Kilmacanogue')
INSERT INTO Team Values(4, 2, 'Kiltegan GAA', 'Kiltegan')
INSERT INTO Team Values(5, 3, 'Laragh GAA', 'Laragh')
INSERT INTO Team Values(6, 3, 'Kilcoole GAA', 'Kilcoole')
INSERT INTO Team Values(7, 4, 'St. Vincents GAA', 'Marino')
INSERT INTO Team Values(8, 4, 'Cuala GAA', 'Dalkey')

--Pitch(ID, Name, Address)
INSERT INTO Pitch Values(1, 'Fitzimons Park', 'Quill Road, Kilmacanogue, Wicklow')
INSERT INTO Pitch Values(2, 'Parc Ui Greystones' , 'Killcarrig, Greystones, Wicklow')